Added MyAtoi
Hidanjkezor/Andersen_tasks pull request #1
Opened 2021-11-03 12:36 UTC by Hidanjkezor

2021-11-03 12:38 UTC, YarikMamykin commented on First_task/First_task.cpp
> +	HRESULT hr = 0;
I guess HRESULT stands for Win32API, which is not available on linux. I believe it can be done simpler.

2021-11-03 12:40 UTC, YarikMamykin commented on First_task/First_task.cpp
> +	for (int i = 0; s[i] >= '0' && s[i] <= '9'; ++i)
What if `const char* s == nullptr` ??

2021-11-03 12:43 UTC, YarikMamykin commented on First_task/First_task.cpp
> +		if (hr == INTSAFE_E_ARITHMETIC_OVERFLOW)
I believe here can be comparison against MAX_INT

2021-11-03 12:43 UTC, YarikMamykin commented on First_task/First_task.cpp
> +	return n;
No exception thrown if conversion is invalid

2021-11-03 12:44 UTC, YarikMamykin commented on First_task/First_task.cpp
> +	const int num5 = MyAtoi(str5);
Maybe it is better to make try-catch block on throwable calls??

2021-11-03 12:45 UTC, YarikMamykin requested changes
Very bad pointer handling. Try better

2021-11-03 14:59 UTC, Hidanjkezor commented on First_task/First_task.cpp
> +	HRESULT hr = 0;
Fixed in {6cf22755}

2021-11-03 15:00 UTC, Hidanjkezor commented on First_task/First_task.cpp
> +	for (int i = 0; s[i] >= '0' && s[i] <= '9'; ++i)
Fixed in {6cf22755}

2021-11-03 15:00 UTC, Hidanjkezor commented on First_task/First_task.cpp
> +		if (hr == INTSAFE_E_ARITHMETIC_OVERFLOW)
Fixed in {6cf22755}

2021-11-03 15:02 UTC, Hidanjkezor commented on First_task/First_task.cpp
> +	return n;
We have come to an agreement that it is not needed

2021-11-03 15:23 UTC, YarikMamykin commented on First_task/First_task.cpp
>  	for (int i = 0; s[i] >= '0' && s[i] <= '9'; ++i)
It is still dangerous to check the 'end' of string like this!
The right way is:
`for(int i = 0; s[i] != '\0'; ++i)`

2021-11-03 19:30 UTC, Hidanjkezor commented on First_task/First_task.cpp
> +	try
Fixing in {61abfb6c}

2021-11-03 19:30 UTC, Hidanjkezor commented on First_task/First_task.cpp
>  	for (int i = 0; s[i] >= '0' && s[i] <= '9'; ++i)
Fixing in {61abfb6c}

2021-11-04 07:25 UTC, YarikMamykin commented on First_task/First_task.cpp
> +				throw std::overflow_error("int overflow with argument: " + static_cast<std::string>(input_value) + "\n");
Take onboard only one style of error processing. Here you have mix of error_code and exceptions. Either always return 0 on error, or throw exception everywhere on error.

2021-11-04 07:26 UTC, YarikMamykin commented on First_task/First_task.cpp
> +			overflow_int_variable = (overflow_int_variable * 10) + (static_cast<long long>(input_value[i]) - '0');
How does it suppose to work and what is the  reason for `static_cast<long long>(const char)` ??

2021-11-04 09:01 UTC, Hidanjkezor commented on First_task/First_task.cpp
> +				throw std::overflow_error("int overflow with argument: " + static_cast<std::string>(input_value) + "\n");
Fixed in {a9a3e20c }

2021-11-04 09:01 UTC, Hidanjkezor commented on First_task/First_task.cpp
> +			overflow_int_variable = (overflow_int_variable * 10) + (static_cast<long long>(input_value[i]) - '0');
Fixed in {a9a3e20c }

2021-11-04 09:28 UTC, YarikMamykin commented on First_task/First_task.cpp
> +	auto p = const_cast<char*>(input_value);
This line of code means that with `p` you can change input data. This is bad approach and bad practice. If you want to iterate through `const char` array just use separate pointer to `const char`.

2021-11-04 09:30 UTC, YarikMamykin commented on First_task/First_task.cpp
> +			throw std::overflow_error("int overflow with argument : " + static_cast<std::string>(input_value) + "\n");
static_cast for const char* is an overdone here. std::string already have respective constructor, which receives const char* as input parameter.

2021-11-04 09:31 UTC, YarikMamykin commented on First_task/First_task.cpp
> +		if(result >INT_MAX /10)
I think for INT_MAX <cstdint> must be included (basically there it is INT32_MAX).

2021-11-04 09:48 UTC, Hidanjkezor commented on First_task/First_task.cpp
> +			throw std::overflow_error("int overflow with argument : " + static_cast<std::string>(input_value) + "\n");
fixed in {f6ec06c8}

2021-11-04 09:48 UTC, Hidanjkezor commented on First_task/First_task.cpp
> +		if(result >INT_MAX /10)
Fixed in {f6ec06c8}

2021-11-04 09:51 UTC, Hidanjkezor commented on First_task/First_task.cpp
> +	auto p = const_cast<char*>(input_value);
Fixed in {f6ec06c8}

2021-11-04 10:19 UTC, YarikMamykin commented on First_task/First_task.cpp
> +	if (*p != '\0') {
seems to be as a check for input parameter, and must be BEFORE any processing

2021-11-04 10:45 UTC, YarikMamykin commented on First_task/First_task.cpp
> +		if(result > INT32_MAX /10)
I believe `INT32_MAX/10` is a constant which can be calculated only once

2021-11-04 11:07 UTC, Hidanjkezor commented on First_task/First_task.cpp
> +		if(result > INT32_MAX /10)
Fixed in {5dd0f16}

2021-11-04 11:09 UTC, Hidanjkezor commented on First_task/First_task.cpp
> +	if (*p != '\0') {
In order to avoid an incorrect answer in accordance with the received agreement

2021-11-04 13:22 UTC, merged