Task 2
Hidanjkezor/Andersen_tasks pull request #2
Opened 2021-11-05 07:42 UTC by Hidanjkezor

2021-11-05 08:18 UTC, YarikMamykin commented on task_2/task_2.cpp
> +        threads.emplace_back(std::move(task),std::cref(matrix), i);
If you pass some function into std::thread it will already be executing asynchronously. So `packaged_task` is an overdone here.

2021-11-05 08:20 UTC, YarikMamykin commented on task_2/task_2.cpp
> +            }
try parsing of matrix row with stringstream and std::getline

2021-11-07 20:11 UTC, Hidanjkezor commented on task_2/task_2.cpp
> +            }
Fixed in {9b0fb86}

2021-11-08 12:03 UTC, YarikMamykin commented on task_2/task_2.cpp
> +		const Matrix a("numbers.txt");
Large objects better to keep in heap

2021-11-08 12:05 UTC, YarikMamykin commented on task_2/Matrix.h
> +	const std::vector<std::vector<int>>& GetMatrix() const;
You can make alias for types to make code more readable. E.g. 
```
using MatrixRow = std::vector<int>;
 const std::vector<MatrixRow>& GetMatrix() const
```

2021-11-08 12:11 UTC, YarikMamykin commented on task_2/Matrix.cpp
> +    }
try using std::for_each here

2021-11-08 12:12 UTC, YarikMamykin commented on task_2/Matrix.cpp
> +    return max_size;
try using std::max with predicate here

2021-11-08 12:24 UTC, YarikMamykin commented on task_2/Matrix.cpp
> +    return results;
I think this code can be reduced with `std::async(std::launch::async, ...)`

2021-11-08 15:17 UTC, Hidanjkezor commented on task_2/task_2.cpp
> +		const Matrix a("numbers.txt");
fixed in {91004d8}

2021-11-08 15:18 UTC, Hidanjkezor commented on task_2/Matrix.h
> +	const std::vector<std::vector<int>>& GetMatrix() const;
fixed in {91004d8}

2021-11-08 15:18 UTC, Hidanjkezor commented on task_2/Matrix.cpp
> +    return max_size;
fixed in {91004d8}

2021-11-08 15:18 UTC, Hidanjkezor commented on task_2/Matrix.cpp
> +    return results;
fixed in {91004d8}

2021-11-09 08:46 UTC, YarikMamykin commented on task_2/Matrix.cpp
> +    matrix_ = SetDefaultMatrix();
No need in default matrix. If file provided doesn't exist - no result is provided.

2021-11-09 08:48 UTC, YarikMamykin requested changes
...

2021-11-09 08:48 UTC, YarikMamykin commented on task_2/Matrix.h
> +	using MatrixRow = std::vector<int>;
Apply this alias in cpp files too

2021-11-09 09:21 UTC, Hidanjkezor commented on task_2/Matrix.cpp
> +    matrix_ = SetDefaultMatrix();
Fixed in  {9f1aa56}

2021-11-09 09:22 UTC, Hidanjkezor commented on task_2/Matrix.h
> +	using MatrixRow = std::vector<int>;
Fixed in  {9f1aa56}

2021-11-23 12:17 UTC, merged